services:
  - type: web
    name: line-bot-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CHANNEL_ACCESS_TOKEN
        value: YOUR_LINE_CHANNEL_ACCESS_TOKEN
      - key: CHANNEL_SECRET
        value: YOUR_LINE_CHANNEL_SECRET
